### PR TITLE
Fix ChoicePrompt ListStyle.none when set via PromptOptions

### PR DESCRIPTION
**Pull request by mdrichardson**
Parity for https://github.com/microsoft/botbuilder-js/pull/1373

There's a couple of tests that weren't passing prior to this change. [There's a test already in place that tests for this, as well.](https://github.com/microsoft/botbuilder-python/blob/master/libraries/botbuilder-dialogs/tests/test_choice_prompt.py#L379)

### CODE REVIEW

**Comment by axelsrz** [comment]
Hey @mdrichardson could you take a look to at step 7 of [this guide ](https://github.com/Microsoft/botbuilder-python/wiki/How-to-Contribute) and check that the PR is compliant with the latest version of the black formatter? Thanks!

**Comment by mdrichardson** [comment]
@axelsrz Done. Not sure if we want to merge yet as the base issue hasn't been merged/approved. My only concern is using an ugly ternary vs. an easier-to-understand if statement.

**Comment by tracyboehrer** [comment]
Can this be merged or is there still an issue?

**Comment by mdrichardson** [comment]
@tracyboehrer I wouldn't say there's an issue so much as the JS PR hasn't been approved. I think it's good to go. @cleemullins, good to merge this and the linked JS PR?

**Comment by cleemullins** [comment]
I've added some reviewers (Axel / Steven). Once one of them signs off (or any qualified reviewer) then we can merge.

**Pull request merged**
