### PR TITLE
add adaptive-expression library

### PR DESCRIPTION
**Pull request by feich-ms**
This PR is to add adaptive expression library in python SDK. Functions and tests are fully aligned with C# and JS version. We can do an official R11 release after reviewed and approved.

**Function list:**
- [x] Math functions
- [x] Comparisons functions
- [x] Logic functions
- [x] String functions
- [x] Collection functions
- [x] DataTime
- [x] Timex
- [x] Conversions
- [x] URI Parsing Functions
- [x] Memory
- [x] Misc
- [x] Object manipulation and construction functions
- [x] Regular expression
- [x] Type Checking

### CODE REVIEW

**Comment by tracyboehrer** [comment]
@feich-ms Thanks!  We'll take a closer look as soon as we can.  One thing to note is that there is some refactoring planned in the dotnet repo for this package.

**Comment by feich-ms** [comment]
@tracyboehrer Thank you very much, I'm still working on adding more expression functions and helpers, but this PR is already a minimun working version with fundamental components. Besides, Is the refactoring work you mentioned above related with this one https://github.com/microsoft/botbuilder-dotnet/pull/4222? If so, I already aligned with this. If not, could you point me the right one?

**Comment by boydc2014** [comment]
@feich-ms can you fix the CI?

**Comment by feich-ms** [comment]
CI failures are fixed and passed now.

**Comment by boydc2014** [comment]
@tracyboehrer @axelsrz  can you help take a look at this, we don't target full feature for this library in R10, but it would be good to get in an init version and verify all the release pipleline all that, then in R11 we can do a official release.

**Comment by tracyboehrer** [comment]
We renamed the master branch to "main".  This PR was originally set to merge to master, but I changed it.  Let me know if you have any issues.

**Comment by feich-ms** [comment]
@vishwacsena, this PR is completely ready now. Functions and tests are fully aligned with C# and JS except the locale-aware ones(locale-aware functions are not much helpful in python library since python library is mainly used by adaptive card team now. We can of course add them when we are at that stage). Please help to prioritize this PR process if its priority is high.

**Comment by vishwacsena** [comment]
@sgellock @cleemullins can we take this for R11? Adaptive cards team had a customer who was looking for this and in general gets us well on the way to get to parity across languages.

**Comment by cleemullins** [comment]
This PR is 206 files and very complex. Please break this down into smaller, focused PRs, and we can review each one individually.

**Comment by sgellock** [comment]
I'd like to re-evaluate if this is still a pressing customer ask, regardless of the PR challenges Chris bring up.

**Comment by sgellock** [comment]
@clearab per I message I sent, can we prioritize the need and urgency?

**Pull request closed without merging**
