### PR TITLE
Fix UnsupportedMediaType in samples

### PR DESCRIPTION
**Pull request by mdrichardson**
Fixes: https://github.com/microsoft/botbuilder-python/issues/312

**Issue Summary**

`request.headers["Content-Type"]` sometimes comes in as 

```
application/json; charset=utf-8
````

...which causes the `415: UnsupportedMediaType` to throw.

**Changes**

In `app.py` for the samples, it implements this diff:

```diff
@app.route("/api/messages", methods=["POST"])
def messages():
    """Main bot message handler."""
-   if request.headers["Content-Type"] == "application/json":
+   if "application/json" in request.headers["Content-Type"]:
        body = request.json
    else:
        return Response(status=415)
```

### CODE REVIEW

**Comment by mdrichardson** [comment]
...working on pylint fixes, although the errors don't appear to be related to this PR

**Comment by axelsrz** [comment]
No, those issues are not related with this PR. I will fix it today and merge this.

**Comment by mdrichardson** [comment]
@axelsrz No further input needed from me, then?

**Comment by axelsrz** [comment]
@mdrichardson no

**Pull request merged**
