### PR TITLE
Naming samples and porting to Flask

### LINKED ISSUE #212: Move samples over to using flask instead of aiohttp
**Describe the solution you'd like**
Move samples over to using `flask`

**Additional context**
Per the [Jet Brains Python Developers Survey for 2018](https://www.jetbrains.com/research/python-developers-survey-2018/), 47% of developers are using Flask with a 15% increase in usage.

jetbrains-2018-web-framework-survey

Additionally, most of the Azure documentation for deploying Python websites to Azure are using Flask (e.g. [Linux App Service via VS Code](https://code.visualstudio.com/docs/python/tutorial-deploy-app-service-on-linux))

[enhancement]

### PR DESCRIPTION
**Pull request by axelsrz**
Ported main samples from aiohttp to Flask. Rename and rearrange of samples to match BotBuilder-Samples.

fixes #212

### CODE REVIEW

**Comment by daveta** [comment]
> pyyaml>=5.1

Curious if this is required?

---
Refers to: samples/06.using-cards/requirements.txt:4 in 557f75c. [](commit_id = 557f75c68cb1a79c218c944831f8c43c3facd134, deletion_comment = False)

**Comment by daveta** [comment]
>       "url": "https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0"

Super low pri: FYI: You can remove the "en-us" and I believe it will redirect appropriately..

---
Refers to: samples/13.core-bot/cards/welcomeCard.json:33 in 557f75c. [](commit_id = 557f75c68cb1a79c218c944831f8c43c3facd134, deletion_comment = False)

**Comment by daveta** [comment]
>     LUIS_API_KEY = ""

Should this have the env check stuff?
ie, `os.environ.get("LuisAPIKey", "")`

---
Refers to: samples/21.corebot-app-insights/config.py:15 in 557f75c. [](commit_id = 557f75c68cb1a79c218c944831f8c43c3facd134, deletion_comment = False)

**Comment by daveta** [comment]
> requests>=2.18.1

We might want to adopt a practice of putting a NOTICE.md (like [here](https://github.com/microsoft/botbuilder-python/blob/master/samples/python_flask/101.corebot-bert-bidaf/NOTICE.md)).  
Specifically, because `requests` has a dependency on a LGPL license.

---
Refers to: samples/21.corebot-app-insights/requirements.txt:3 in 557f75c. [](commit_id = 557f75c68cb1a79c218c944831f8c43c3facd134, deletion_comment = False)

**Comment by daveta** [comment]
> # -c "from model_corebot101.language_helper import LanguageHelper; lh = LanguageHelper(). lh.initialize_models(bert_model_dir='/model_runtime_api/model/bert', bidaf_model_dir='/model_runtime_api/model/bidaf')"

Doh!  Not needed.  

---
Refers to: samples/experimental/101.corebot-bert-bidaf/Dockerfile_model_runtime:27 in 557f75c. [](commit_id = 557f75c68cb1a79c218c944831f8c43c3facd134, deletion_comment = False)

**Comment by axelsrz** [comment]
fixed comments @daveta

**Pull request merged**
