### PR TITLE
Returning callback to get activity on proactive message send

### LINKED ISSUE #2153: Can't get activity ID when using ADAPTER.continue_conversation
## Version
botbuilder-core==4.16.1

## Describe the bug
When making proactive message with

```
activity_id = await ADAPTER.continue_conversation(
    reference,
    lambda turn_context: turn_context.send_activity(message),
    CONFIG.APP_ID,
)
print(activity_id)
```

it doesn't return anything, but I need to save activity id to update the message later

## To Reproduce
Use sample from https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/16.proactive-messages/app.py#L87

When calling wait ADAPTER.continue_conversation save results to var like mentioned above.

## Expected behavior
I expect to have activity object to be able to save ID to modify this message later.

## Additional context
I can try to put a PR for this

### PR DESCRIPTION
**Pull request by Attels**
Fixes #2153 

## Description
Adding return statement to receive callback execution result to get activity id

### CODE REVIEW

**Comment by Attels** [comment]
> @Attels please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by Attels** [comment]
@tracyboehrer could you kindly take a look at this PR

**Comment by tracyboehrer** [comment]
Well, the callback doesn't return anything.  That is, the Bot.on_turn.  If it did, what would it return?  This is the same across all SDK language versions and not something we could change without likely breaking builds.

**Comment by Attels** [comment]
@tracyboehrer the callback in my case is turn_context.send_activity(message), and it returns the sent message's id. 

See example below: 

```
activity_id = await ADAPTER.continue_conversation(
    reference,
    lambda turn_context: turn_context.send_activity(message),
    CONFIG.APP_ID,
)
print(activity_id)
```

If that's not the right approach, how could I get the ID of the message I sent from ADAPTER.continue_conversation when sending a proactive message? 

Thanks in advance.

**Pull request closed without merging**
