### PR TITLE
updating dependencies

### LINKED ISSUE #1467: BotBuilder, as a library, should not pin 3rd party dependencies
## Version
4.11.0

## Describe the bug
I'm trying to add BotBuilder to an app that already has ibm-watson as a dependency.
The conflict is due to botbuilder-core pinning a very old version of `PyJWT`.
ibm-watson needs ibm-cloud-sdk-core which needs PyJWT. ibm-cloud-sdk-core uses a range of versions, specifying `PyJWT>=2.0.0a1,<3.0.0` in the last few versions, but for all older versions, it required `PyJWT>=1.7.1`.

https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botframework-connector/setup.py#L12

BotBuilder is a library meant to be embedded in other applications, so pinning 3rd party deps is dangerous.
Looking through the dependencies in the various botbuilder libraries, it looks like several have dependencies that are pinned instead of specifying a range of valid versions. For the microsoft-provided deps, pinning makes perfect sense. For 3rd party deps, please do not pin the dep version (instead specify a range) and allow the application that is using the botbuilder framework to pin its own deps

## To Reproduce
1. `pip install --upgrade pip` (in a virtualenv) _to use the new resolver that refuses to install conflicting dependencies_
2. `pip install ibm-watson botbuilder-core==4.11.0`
3.  pip backtracks for awhile until it gets to some very old versions of ibm-watson that it can't process and dies.
4. even if pip could process the old versions, no version of the ibm lib ever supported version 1.5.3 of PyJWT that was released in 2018.

## Expected behavior
For microsoft/azure libraries, go ahead and pin the deps. The botbuilder itself is versioned together, so pinning makes perfect sense.

If you want to pin the version 3rd party deps in requirements.txt, that also is fine so that you can say "This is the most tested/supported version". But please, in `setup.py`, specify a range of valid versions for 3rd party deps to ease integrating BotBuilder in existing applications.

## Additional context
Here are the 3rd party dependency lines in setup.py that pin 3rd party deps in 4.11.0 (the deps are still pinned in main/4.12.0):

### PyJWT, requests, cryptography
_very common packages, likely to cause conflicts. **Caused a conflict for me**_
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botframework-connector/setup.py#L10-L12

### aiohttp
_very common package, likely to cause conflicts_
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-integration-aiohttp/setup.py#L12
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py#L9
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-ai/setup.py#L11
Unpinning aiohttp in `botbuilder-ai`also requires bumping the required version of aioresponses to at least `0.7.1` to get this fix https://github.com/pnuckowski/aioresponses/pull/174 (adds support for aiohttp 3.7+):
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-ai/tests/requirements.txt#L1

### babel
_common package, likely to cause conflicts_
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-dialogs/setup.py#L14

### jsonpickle
_less common package, so I'm not as concerned._
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-core/setup.py#L11
https://github.com/microsoft/botbuilder-python/blob/11b08778beb6f3d31c65fb35b54beabb89fb4bdc/libraries/botbuilder-azure/setup.py#L12

### LINKED ISSUE #1620: Incorrect adal requirement in botframework-connector setup.py
## Version
botframework-connector 4.12.0

## Describe the bug
While looking into dependencies installed by botframework-connector I saw that deprecated **adal** in addition to **msal**. 

The _requirements.txt_ does not have this requirement but [setup.py does](https://github.com/microsoft/botbuilder-python/blob/293916fa96b147cf2cd0ef4726a2ddd0605b9155/libraries/botframework-connector/setup.py#L15)

I did a quick github search and no reference to adal and looks like it was replaced with msal here: https://github.com/microsoft/botbuilder-python/commit/5a622806f3d5b0e39d16fc3de948fe469ff81c8f

## To Reproduce
    pip install botframework-connector

## Expected behavior
No unneeded pip packages

### PR DESCRIPTION
**Pull request by axelsrz**
Fixes #1467 
Fixed #1620

### CODE REVIEW

**Comment by danitico** [comment]
Any updates on when this fix will be released? @axelsrz

**Comment by romerox3** [comment]
Hi @axelsrz! We've been waiting a couple of weeks for this. Do you know when it will be included?

**Review by tracyboehrer — APPROVED** [review]

**Comment by cas--** [comment]
While updating deps, perhaps include this botframework-connector fix: https://github.com/microsoft/botbuilder-python/issues/1620

**Pull request merged**
